# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-07 06:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_name', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
                ('filetype', models.CharField(max_length=20)),
                ('size', models.IntegerField(default=0)),
                ('author', models.CharField(max_length=20)),
                ('votes', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='RefTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='reference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='refinator.Reference'),
        ),
    ]
