# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-07 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('refinator', '0001_initial'), ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='tags',
            field=models.ManyToManyField(to='refinator.RefTag'), ),
    ]
