# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-07 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refinator', '0002_reference_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='reftag',
            name='tag_slug',
            field=models.CharField(default='kek', max_length=100),
            preserve_default=False,
        ),
    ]
