# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-08 00:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('refinator', '0003_reftag_tag_slug'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RefTag',
            new_name='Tag',
        ),
    ]
