# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-08 03:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refinator', '0005_auto_20161008_0325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reference',
            name='followups',
        ),
        migrations.AddField(
            model_name='reference',
            name='followups',
            field=models.ManyToManyField(blank=True, null=True, related_name='_reference_followups_+', to='refinator.Reference'),
        ),
        migrations.RemoveField(
            model_name='reference',
            name='prereqs',
        ),
        migrations.AddField(
            model_name='reference',
            name='prereqs',
            field=models.ManyToManyField(blank=True, null=True, related_name='_reference_prereqs_+', to='refinator.Reference'),
        ),
        migrations.RemoveField(
            model_name='reference',
            name='read_with',
        ),
        migrations.AddField(
            model_name='reference',
            name='read_with',
            field=models.ManyToManyField(blank=True, null=True, related_name='_reference_read_with_+', to='refinator.Reference'),
        ),
    ]
