# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-08 07:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('refinator', '0007_reference_desc'), ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='followups',
            field=models.ManyToManyField(
                blank=True,
                related_name='_reference_followups_+',
                to='refinator.Reference'), ),
        migrations.AlterField(
            model_name='reference',
            name='prereqs',
            field=models.ManyToManyField(
                blank=True,
                related_name='_reference_prereqs_+',
                to='refinator.Reference'), ),
        migrations.AlterField(
            model_name='reference',
            name='read_with',
            field=models.ManyToManyField(
                blank=True,
                related_name='_reference_read_with_+',
                to='refinator.Reference'), ),
    ]
