# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-08 12:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refinator', '0009_comment_speaker'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.date(2016, 10, 8)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reference',
            name='added_date',
            field=models.DateField(auto_now_add=True, default=datetime.date(2016, 10, 8)),
            preserve_default=False,
        ),
    ]
