# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-08 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refinator', '0010_auto_20161008_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='desc',
            field=models.CharField(default='', max_length=5000),
        ),
    ]
