# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-09 03:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('refinator', '0011_tag_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='added_by',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL), ),
    ]
