# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-09 04:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('refinator', '0014_auto_20161009_0351'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenceVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='', max_length=5000)),
            ],
        ),
        migrations.RemoveField(
            model_name='reference',
            name='votes',
        ),
        migrations.AddField(
            model_name='referencevote',
            name='ref',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='refinator.Reference'),
        ),
        migrations.AddField(
            model_name='referencevote',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
