# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-09 04:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refinator', '0015_auto_20161009_0415'),
    ]

    operations = [
        migrations.AddField(
            model_name='referencevote',
            name='vote_amount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
