# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-11 07:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('refinator', '0018_auto_20161011_0718'), ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='followups',
            field=models.ManyToManyField(
                blank=True,
                related_name='followup_for',
                to='refinator.Reference'), ),
        migrations.AddField(
            model_name='reference',
            name='prereqs',
            field=models.ManyToManyField(
                blank=True,
                related_name='prereq_for',
                to='refinator.Reference'), ),
        migrations.AddField(
            model_name='reference',
            name='read_with',
            field=models.ManyToManyField(
                blank=True,
                related_name='read_with_for',
                to='refinator.Reference'), ),
    ]
