# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-11 08:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refinator', '0019_auto_20161011_0718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='reference',
            name='desc',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='tag',
            name='desc',
            field=models.TextField(),
        ),
    ]
