# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-11 08:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('refinator',
         '0021_historicalcomment_historicalreference_historicaltag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalcomment',
            name='history_user', ),
        migrations.RemoveField(
            model_name='historicalcomment',
            name='reference', ),
        migrations.RemoveField(
            model_name='historicalcomment',
            name='speaker', ),
        migrations.RemoveField(
            model_name='historicalreference',
            name='added_by', ),
        migrations.RemoveField(
            model_name='historicalreference',
            name='history_user', ),
        migrations.RemoveField(
            model_name='historicaltag',
            name='history_user', ),
        migrations.DeleteModel(
            name='HistoricalComment', ),
        migrations.DeleteModel(
            name='HistoricalReference', ),
        migrations.DeleteModel(
            name='HistoricalTag', ),
    ]
